web:
  build: .
  command: foreman start -f Procfile.dev
  volumes:
    - .:/code/web
  ports:
    - 80:3000
  links:
    - postgres
  stdin_open: true
  tty: true
  volumes_from:
    - bundle

bundle:
  image: rails_web
  command: echo "I'm a little data container, for persisting bundles."
  volumes:
    - /bundle

postgres:
  image: postgres:9.5.3
  ports:
    - 5432
