app:
  build: .
  command: foreman start -f Procfile.dev
  volumes:
    - .:/code/vmware_ma
  ports:
    - 80:3000
  links:
    - postgres
  stdin_open: true
  tty: true

postgres:
  image: postgres:9.5.3
  ports:
    - 5432
